terraform {
  required_version = ">= 1.3.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# ---------------------------------------------------------------------------
# Provider — points at LocalStack when LOCALSTACK_ENDPOINT is set,
# otherwise uses real AWS credentials from the environment.
# ---------------------------------------------------------------------------
provider "aws" {
  region                      = var.aws_region
  access_key                  = var.localstack_mode ? "test" : null
  secret_key                  = var.localstack_mode ? "test" : null
  skip_credentials_validation = var.localstack_mode
  skip_metadata_api_check     = var.localstack_mode
  skip_requesting_account_id  = var.localstack_mode

  dynamic "endpoints" {
    for_each = var.localstack_mode ? [1] : []
    content {
      s3       = var.localstack_endpoint
      dynamodb = var.localstack_endpoint
      sns      = var.localstack_endpoint
      sqs      = var.localstack_endpoint
      lambda   = var.localstack_endpoint
      iam      = var.localstack_endpoint
    }
  }
}

# ---------------------------------------------------------------------------
# One isolated test environment module per test-run prefix.
# The prefix is generated by conftest.py so each CI run is hermetic.
# ---------------------------------------------------------------------------
module "sports_pipeline_env" {
  source = "./modules/sports-pipeline-env"

  run_prefix   = var.run_prefix
  aws_region   = var.aws_region
  environment  = var.environment
  enable_alerts = var.enable_alerts
}
