variable "run_prefix" {
  description = "Unique prefix per test run — ensures full isolation between parallel runs."
  type        = string
  # Generated by conftest.py: e.g. "ht-20240405-a3f9"
}

variable "aws_region" {
  description = "AWS region for the test environment."
  type        = string
  default     = "us-east-1"
}

variable "environment" {
  description = "Environment tag applied to all resources."
  type        = string
  default     = "test"
}

variable "localstack_mode" {
  description = "When true the provider targets LocalStack instead of real AWS."
  type        = bool
  default     = true
}

variable "localstack_endpoint" {
  description = "LocalStack gateway URL."
  type        = string
  default     = "http://localhost:4566"
}

variable "enable_alerts" {
  description = "Create SNS + SQS notification pipeline in the test environment."
  type        = bool
  default     = true
}
